### PR TITLE
add support for (disabling) symmetrisation to readbinarycf

### PR DESCRIPTION
**Pull request by kostrzewa**

### CODE REVIEW

**Comment by kostrzewa** [comment]
@urbach: maybe we can move to having the main hadron repository here?

**Comment by urbach** [comment]
> @urbach: maybe we can move to having the main hadron repository here?

fine with me, if you want... (though its not really ETMC software...)

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/etmc/hadron/pull/20#issuecomment-362233196
--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by martin-ueding** [comment]
Alternatively we could make this on the `etmc` organization the main repository, delete the one on your `urbach` account and then move the `etmc` repository (with issues and pull requests) to the your `urbach` account?

**Comment by urbach** [comment]
its fine with the etmc organisation one, I don't care...

> Alternatively we could make this on the `etmc` organization the main repository, delete the one on your `urbach` account and then move the `etmc` repository (with issues and pull requests) to the your `urbach` account?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/etmc/hadron/pull/20#issuecomment-365296473
--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Pull request merged**
